# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Update Code and Deploy to Prefect

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"                   # set this to your preferred AWS region, e.g. us-west-1

jobs:
  install:
    name: Install CI/CD Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2     # default
          verbose: false # default
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Display AWS CLI version
        run: aws --version
        
  build:
    needs: install
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install requirements.txt
        run: |
          python -m pip install tea "cup >= 3.2.13"
          pip install -r requirements.txt
      - name: Set environment variables
        run: |
          echo "SFUSER=${{ secrets.SFUSER }}" >> "$GITHUB_ENV"
          echo "SFPW=${{ secrets.SFPW }}" >> "$GITHUB_ENV"
          echo "SNOWFLAKE_ACCT=${{ secrets.SNOWFLAKE_ACCT }}" >> "$GITHUB_ENV"
          echo "SFWH=${{ secrets.SFWH }}" >> "$GITHUB_ENV"
          echo "SNOWFLAKE_DB=${{ secrets.SNOWFLAKE_DB }}" >> "$GITHUB_ENV"
          echo "SFSCHEMA=${{ secrets.SFSCHEMA }}" >> "$GITHUB_ENV"
          
          # SET THE PYTHONPATH TO THIS WORKSPACE
          echo "PYTHONPATH=${PYTHONPATH}:/home/runner/work/NHL-Database/NHL-Database/" >> "$GITHUB_ENV"
          
      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: ${{ secrets.PREFECT_WORKSPACE }}
      - name: Prefect Dry-Run
        run: |
          python3 src/scripts/snowflake_transfer.py seasons
          
  deploy:
    needs: build
    name: Run Prefect Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prefect 
        uses: PrefectHQ/actions-prefect-deploy@v3
        with:
          deployment-names: Simple
          requirements-file-paths: ./requirements.txt
          prefect-file: ./prefect.yaml
